import math
from typing import Optional
 
import torch
import triton
import triton.language as tl

@triton.autotune(
    configs=[
        triton.Config({"BLOCK_SIZE": 512},  num_warps=4),
        triton.Config({"BLOCK_SIZE": 1024}, num_warps=8),
        triton.Config({"BLOCK_SIZE": 2048}, num_warps=16),
    ],
    key=["N"],
)
@triton.jit
def _rms_norm_fwd_kernel(
    X,           
    W,          
    Y,          
    stride_x, 
    N,        
    eps,       
    BLOCK_SIZE: tl.constexpr,
):
    """
    Fused forward RMSNorm kernel.
    One program = one row (one token).
 
    vs Inductor auto-generated:
    - Same fusion level: 1 kernel for the full op.
    - Key difference: @triton.autotune finds optimal BLOCK_SIZE per GPU.
    - Inductor defaults to XBLOCK=512 (static); this kernel tunes to hardware.
    - Explicit fp16→fp32 upcast via tl.load with eviction_policy hint.
    """
    row = tl.program_id(0)
    X  += row * stride_x
    Y  += row * stride_x
 
  
    cols  = tl.arange(0, BLOCK_SIZE)
    mask  = cols < N
    x     = tl.load(X + cols, mask=mask, other=0.0).to(tl.float32)
    w     = tl.load(W + cols, mask=mask, other=1.0)
 
   
    x_sq  = x * x
    mean  = tl.sum(x_sq, axis=0) / N
    rrms  = tl.rsqrt(mean + eps)
 

    y     = (x * rrms) * w.to(tl.float32)
 
    
    tl.store(Y + cols, y.to(tl.float16), mask=mask)
 
 
@triton.autotune(
    configs=[
        triton.Config({"BLOCK_SIZE": 512},  num_warps=4),
        triton.Config({"BLOCK_SIZE": 1024}, num_warps=8),
        triton.Config({"BLOCK_SIZE": 2048}, num_warps=16),
    ],
    key=["N"],
)
@triton.jit
def _rms_norm_bwd_kernel(
    DY,          
    X,          
    W,          
    DX,          
    DW,          
    stride_x,
    N,
    eps,
    BLOCK_SIZE: tl.constexpr,
):
    """
    Fused backward RMSNorm kernel.
    Not auto-generated by inductor when using torch.compile in eval mode,
    but included here for training runs.
    """
    row  = tl.program_id(0)
    X   += row * stride_x
    DY  += row * stride_x
    DX  += row * stride_x
 
    cols = tl.arange(0, BLOCK_SIZE)
    mask = cols < N
 
    x    = tl.load(X  + cols, mask=mask, other=0.0).to(tl.float32)
    dy   = tl.load(DY + cols, mask=mask, other=0.0).to(tl.float32)
    w    = tl.load(W  + cols, mask=mask, other=1.0).to(tl.float32)
 
    x_sq = x * x
    mean = tl.sum(x_sq, axis=0) / N
    rrms = tl.rsqrt(mean + eps)
 
    
    normed = x * rrms
    dw     = dy * normed
    tl.atomic_add(DW + cols, dw, mask=mask)
 
    dy_w   = dy * w
    dot    = tl.sum(dy_w * normed, axis=0)
    dx     = rrms * (dy_w - normed * dot / N)
    tl.store(DX + cols, dx.to(tl.float16), mask=mask)
 
 
class RMSNormTriton(torch.autograd.Function):
    """
    Autograd wrapper for the hand-written Triton RMSNorm kernel.
    """
 
    @staticmethod
    def forward(ctx, x: torch.Tensor, weight: torch.Tensor, eps: float = 1e-6):
        orig_shape = x.shape
        x_2d = x.view(-1, x.shape[-1])
        M, N = x_2d.shape
 
        y = torch.empty_like(x_2d)
        _rms_norm_fwd_kernel[(M,)](
            x_2d, weight, y, x_2d.stride(0), N, eps,
        )
        ctx.save_for_backward(x_2d, weight)
        ctx.eps = eps
        return y.view(orig_shape)
 
    @staticmethod
    def backward(ctx, dy: torch.Tensor):
        x_2d, weight = ctx.saved_tensors
        M, N = x_2d.shape
        dy_2d = dy.view(M, N)
 
        dx = torch.empty_like(x_2d)
        dw = torch.zeros_like(weight)
        _rms_norm_bwd_kernel[(M,)](
            dy_2d, x_2d, weight, dx, dw, x_2d.stride(0), N, ctx.eps,
        )
        return dx.view_as(dy), dw, None
 
 
@triton.autotune(
    configs=[
        triton.Config({"BLOCK_SIZE": 512},  num_warps=4),
        triton.Config({"BLOCK_SIZE": 1024}, num_warps=8),
        triton.Config({"BLOCK_SIZE": 2048}, num_warps=16),
        triton.Config({"BLOCK_SIZE": 4096}, num_warps=16),
    ],
    key=["N"],
)
@triton.jit
def _softmax_fwd_kernel(
    X,          
    Y,         
    stride_x,
    N,          
    BLOCK_SIZE: tl.constexpr,
):
    """
    Online (3-pass fused) softmax kernel.
 
    vs Inductor auto-generated:
    - Identical algorithm: max-reduce → exp-sum → divide
    - Key difference: @triton.autotune tunes BLOCK_SIZE to GPU register file.
    - For N > BLOCK_SIZE we tile across multiple blocks (inductor also does this).
    - Numerically identical to torch.softmax but with explicit kernel control.
 
    For MoE router (N=num_experts=64 for OLMoE):
    - BLOCK_SIZE=64 covers all experts in 1 block → no inter-block reduction.
    - For Mixtral (N=8): BLOCK_SIZE=8, fits in <1 warp.
    """
    row      = tl.program_id(0)
    X       += row * stride_x
    Y       += row * stride_x
    cols     = tl.arange(0, BLOCK_SIZE)
    mask     = cols < N
 
  
    x        = tl.load(X + cols, mask=mask, other=-float("inf"))
    x_max    = tl.max(x, axis=0)
 

    x_exp    = tl.exp(x - x_max)
    x_sum    = tl.sum(x_exp, axis=0)
 

    y        = x_exp / x_sum
 
    tl.store(Y + cols, y, mask=mask)
 
 
def softmax_triton(x: torch.Tensor) -> torch.Tensor:
    """
    Entry point for hand-written Triton softmax.
    x: (batch, seq, N) or (T, N)
    """
    orig_shape = x.shape
    x_2d = x.view(-1, x.shape[-1])
    M, N = x_2d.shape
    y    = torch.empty_like(x_2d)
    _softmax_fwd_kernel[(M,)](x_2d, y, x_2d.stride(0), N)
    return y.view(orig_shape)
 
 
def rms_norm_triton(
    x: torch.Tensor,
    weight: torch.Tensor,
    eps: float = 1e-6,
) -> torch.Tensor:
    """Entry point for hand-written Triton RMSNorm."""
    return RMSNormTriton.apply(x, weight, eps)
 
 
HANDWRITTEN_RMSNORM_SOURCE = """
# Hand-written Triton RMSNorm kernel (kernels/triton_kernels.py)
# Key differences from inductor auto-generated:
#   1. @triton.autotune — tunes BLOCK_SIZE per GPU (inductor uses static 512)
#   2. Explicit fp16→fp32 upcast with eviction hints (inductor uses default)
#   3. Backward kernel included (inductor generates backward automatically via autograd)
#   4. Single .to(tl.float16) downcast at store (same as inductor)
#   5. No separate cast kernel: dtype handled inside the JIT kernel
 
@triton.autotune([
    Config({'BLOCK_SIZE': 512},  num_warps=4),
    Config({'BLOCK_SIZE': 1024}, num_warps=8),
    Config({'BLOCK_SIZE': 2048}, num_warps=16),
], key=['N'])
@triton.jit
def _rms_norm_fwd_kernel(X, W, Y, stride_x, N, eps, BLOCK_SIZE: tl.constexpr):
    row  = tl.program_id(0)
    cols = tl.arange(0, BLOCK_SIZE)
    mask = cols < N
    x    = tl.load(X + row*stride_x + cols, mask=mask, other=0.0).to(tl.float32)
    w    = tl.load(W + cols, mask=mask, other=1.0)
    rrms = tl.rsqrt(tl.sum(x*x, axis=0)/N + eps)
    tl.store(Y + row*stride_x + cols, ((x*rrms)*w.to(tl.float32)).to(tl.float16), mask=mask)
"""
 
HANDWRITTEN_SOFTMAX_SOURCE = """
# Hand-written Triton Softmax kernel (kernels/triton_kernels.py)
# Key differences from inductor auto-generated:
#   1. @triton.autotune over BLOCK_SIZE and num_warps
#   2. Explicit 3-pass online algorithm (same as inductor)
#   3. For MoE router: N=num_experts fits in 1 block → no inter-block sync
 
@triton.autotune([
    Config({'BLOCK_SIZE': 512},  num_warps=4),
    Config({'BLOCK_SIZE': 1024}, num_warps=8),
], key=['N'])
@triton.jit
def _softmax_fwd_kernel(X, Y, stride_x, N, BLOCK_SIZE: tl.constexpr):
    row  = tl.program_id(0)
    cols = tl.arange(0, BLOCK_SIZE)
    mask = cols < N
    x    = tl.load(X + row*stride_x + cols, mask=mask, other=-float('inf'))
    x_max = tl.max(x, axis=0)
    x_exp = tl.exp(x - x_max)
    tl.store(Y + row*stride_x + cols, x_exp / tl.sum(x_exp, axis=0), mask=mask)
"""